"""add zipcode to delivery_partner

Revision ID: 1a5ca1072361
Revises: 637e1fd106e5
Create Date: 2026-07-31 20:17:03.924953

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a5ca1072361'
down_revision: Union[str, Sequence[str], None] = '637e1fd106e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delivery_partner', sa.Column('zipcode', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('delivery_partner', 'zipcode')
    # ### end Alembic commands ###
